import type { PlatformServiceRegistration, PlatformCapability } from "@grayscale/platform";

export const PLATFORM_SERVICES: Omit<PlatformServiceRegistration, "status">[] = [
  {
    id: "event-store",
    name: "Event Store",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Immutable domain event persistence and replay",
    owner: "platform-core",
    module: "EventsModule",
    capabilities: ["events.read", "events.replay"],
    dependencies: [],
    routes: [{ method: "GET", path: "/companies/:companyId/events", description: "Event history" }],
    documentation: "docs/platform/EVENT_CATALOG.md",
  },
  {
    id: "memory-engine",
    name: "Memory Engine",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Unified memory index and cross-type search",
    owner: "platform-core",
    module: "MemoryModule",
    capabilities: ["memory.search", "memory.recent"],
    dependencies: ["event-store"],
    routes: [
      { method: "GET", path: "/companies/:companyId/memory/search" },
      { method: "GET", path: "/companies/:companyId/memory/recent" },
    ],
    documentation: "docs/platform/MEMORY_ENGINE.md",
  },
  {
    id: "knowledge-graph",
    name: "Knowledge Graph",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Entity graph traversal, search, and analytics",
    owner: "platform-core",
    module: "GraphModule",
    capabilities: ["graph.traversal", "graph.summary"],
    dependencies: ["event-store", "memory-engine"],
    routes: [
      { method: "GET", path: "/companies/:companyId/graph/summary" },
      { method: "GET", path: "/companies/:companyId/graph/health" },
    ],
    documentation: "docs/platform/KNOWLEDGE_GRAPH.md",
  },
  {
    id: "strategic-intelligence",
    name: "Strategic Intelligence",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Goals, recommendations, priorities, and strategy engines",
    owner: "platform-core",
    module: "IntelligenceModule",
    capabilities: [
      "intelligence.strategy",
      "intelligence.recommendations",
      "intelligence.goals",
      "intelligence.priorities",
    ],
    dependencies: ["memory-engine", "knowledge-graph"],
    routes: [{ method: "GET", path: "/companies/:companyId/intelligence/summary" }],
    documentation: "docs/api/INTELLIGENCE_API.md",
  },
  {
    id: "executive-runtime",
    name: "Executive Runtime",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Executive lifecycle, context assembly, and bus",
    owner: "platform-core",
    module: "ExecutiveModule",
    capabilities: ["executive.context", "executive.status"],
    dependencies: ["strategic-intelligence", "memory-engine", "pulse-engine"],
    routes: [{ method: "GET", path: "/companies/:companyId/executive-runtime/context" }],
    documentation: "docs/architecture/EXECUTIVE_RUNTIME.md",
  },
  {
    id: "integration-platform",
    name: "Integration Platform",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Connectors, sync, normalization, and plugin runtime",
    owner: "platform-core",
    module: "IntegrationPlatformModule",
    capabilities: ["integration.health", "integration.sync", "plugin.install"],
    dependencies: ["event-store"],
    routes: [{ method: "GET", path: "/companies/:companyId/platform/integrations/health" }],
    documentation: "docs/api/PLATFORM_INTEGRATION_API.md",
  },
  {
    id: "pulse-engine",
    name: "Pulse Engine",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Operational heartbeats and company health aggregation",
    owner: "platform-core",
    module: "PulseModule",
    capabilities: ["pulse.stream", "pulse.health"],
    dependencies: ["event-store"],
    routes: [
      { method: "GET", path: "/companies/:companyId/pulse/health" },
      { method: "GET", path: "/companies/:companyId/pulse/stream" },
    ],
    documentation: "docs/architecture/CORE_PLATFORM_DESIGN_REVIEW.md",
  },
  {
    id: "timeline",
    name: "Timeline",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Company timeline events and scheduling",
    owner: "platform-core",
    module: "TimelineModule",
    capabilities: ["timeline.recent", "timeline.create"],
    dependencies: ["event-store"],
    routes: [{ method: "GET", path: "/companies/:companyId/timeline" }],
    documentation: "docs/platform/EVENT_CATALOG.md",
  },
  {
    id: "billing",
    name: "Billing",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Bill tracking and payment reminders",
    owner: "platform-core",
    module: "BillingModule",
    capabilities: ["billing.upcoming", "billing.create"],
    dependencies: [],
    routes: [{ method: "GET", path: "/companies/:companyId/bills" }],
    documentation: "docs/platform/EVENT_CATALOG.md",
  },
  {
    id: "notifications",
    name: "Notifications",
    version: "1.0.0",
    apiVersion: "v1",
    description: "User notifications and alerts",
    owner: "platform-core",
    module: "NotificationsModule",
    capabilities: ["notification.unread"],
    dependencies: [],
    routes: [{ method: "GET", path: "/notifications" }],
    documentation: "docs/platform/EVENT_CATALOG.md",
  },
  {
    id: "mission-control",
    name: "Mission Control",
    version: "1.0.0",
    apiVersion: "v1",
    description: "Operational command center aggregation and actions",
    owner: "platform-core",
    module: "MissionControlModule",
    capabilities: ["operations.dashboard", "operations.actions", "operations.search"],
    dependencies: ["pulse-engine", "strategic-intelligence", "integration-platform"],
    routes: [{ method: "GET", path: "/companies/:companyId/mission-control/dashboard" }],
    documentation: "docs/api/MISSION_CONTROL_API.md",
  },
];

export const PLATFORM_CAPABILITIES: PlatformCapability[] = [
  { id: "memory.search", name: "Memory Search", category: "memory", serviceId: "memory-engine", route: "/companies/:companyId/memory/search", searchable: true, keywords: ["memory", "search", "notes"] },
  { id: "memory.recent", name: "Recent Memory", category: "memory", serviceId: "memory-engine", route: "/companies/:companyId/memory/recent", searchable: true, keywords: ["recent", "memory"] },
  { id: "graph.traversal", name: "Graph Traversal", category: "graph", serviceId: "knowledge-graph", route: "/companies/:companyId/graph/nodes/:id/expand", searchable: true, keywords: ["graph", "traverse"] },
  { id: "graph.summary", name: "Graph Summary", category: "graph", serviceId: "knowledge-graph", route: "/companies/:companyId/graph/summary", searchable: true, keywords: ["graph", "summary"] },
  { id: "intelligence.strategy", name: "Strategy Analysis", category: "intelligence", serviceId: "strategic-intelligence", route: "/companies/:companyId/intelligence/summary", searchable: true, keywords: ["strategy", "analysis"] },
  { id: "intelligence.recommendations", name: "Recommendations", category: "intelligence", serviceId: "strategic-intelligence", route: "/companies/:companyId/intelligence/recommendations", searchable: true, keywords: ["recommendations"] },
  { id: "intelligence.goals", name: "Goals", category: "intelligence", serviceId: "strategic-intelligence", route: "/companies/:companyId/intelligence/goals", searchable: true, keywords: ["goals", "objectives"] },
  { id: "intelligence.priorities", name: "Priorities", category: "intelligence", serviceId: "strategic-intelligence", route: "/companies/:companyId/intelligence/priorities", searchable: true, keywords: ["priorities"] },
  { id: "integration.health", name: "Integration Health", category: "integration", serviceId: "integration-platform", route: "/companies/:companyId/platform/integrations/health", searchable: true, keywords: ["integration", "health"] },
  { id: "integration.sync", name: "Integration Sync", category: "integration", serviceId: "integration-platform", route: "/companies/:companyId/platform/integrations/:provider/sync", searchable: true, keywords: ["sync", "integration"] },
  { id: "plugin.install", name: "Plugin Install", category: "plugin", serviceId: "integration-platform", searchable: true, keywords: ["plugin", "install"] },
  { id: "executive.context", name: "Executive Context", category: "executive", serviceId: "executive-runtime", route: "/companies/:companyId/executive-runtime/context", searchable: true, keywords: ["executive", "context"] },
  { id: "executive.status", name: "Executive Status", category: "executive", serviceId: "executive-runtime", route: "/companies/:companyId/executive-runtime/status", searchable: true, keywords: ["executive", "status"] },
  { id: "billing.upcoming", name: "Upcoming Bills", category: "billing", serviceId: "billing", route: "/companies/:companyId/bills", searchable: true, keywords: ["bills", "billing"] },
  { id: "timeline.recent", name: "Timeline Events", category: "timeline", serviceId: "timeline", route: "/companies/:companyId/timeline", searchable: true, keywords: ["timeline", "events"] },
  { id: "timeline.create", name: "Create Timeline Event", category: "timeline", serviceId: "timeline", searchable: false },
  { id: "notification.unread", name: "Unread Notifications", category: "notification", serviceId: "notifications", route: "/notifications", searchable: true, keywords: ["notifications"] },
  { id: "pulse.stream", name: "Pulse Stream", category: "operations", serviceId: "pulse-engine", route: "/companies/:companyId/pulse/stream", searchable: true, keywords: ["pulse", "stream"] },
  { id: "pulse.health", name: "Pulse Health", category: "operations", serviceId: "pulse-engine", route: "/companies/:companyId/pulse/health", searchable: true, keywords: ["pulse", "health"] },
  { id: "operations.dashboard", name: "Mission Control Dashboard", category: "operations", serviceId: "mission-control", route: "/companies/:companyId/mission-control/dashboard", searchable: true, keywords: ["dashboard", "mission control"] },
  { id: "operations.actions", name: "Platform Actions", category: "operations", serviceId: "mission-control", route: "/companies/:companyId/mission-control/actions", searchable: true, keywords: ["actions"] },
  { id: "operations.search", name: "Global Search", category: "search", serviceId: "mission-control", route: "/companies/:companyId/mission-control/search", searchable: true, keywords: ["search", "global"] },
  { id: "events.read", name: "Event History", category: "operations", serviceId: "event-store", searchable: true, keywords: ["events", "history"] },
];
