import { Injectable } from "@nestjs/common";
import type { MissionControlWidgetDefinition, WidgetInstanceConfig } from "@grayscale/platform";

export const DEFAULT_WIDGETS: MissionControlWidgetDefinition[] = [
  {
    id: "platform-health",
    name: "Platform Health",
    category: "health",
    dataProvider: "platform-health",
    refreshPolicy: { mode: "polling", intervalSeconds: 30 },
    permissions: [],
    layout: { defaultWidth: 2, defaultHeight: "compact", order: 0, collapsible: false, resizable: true, exportable: true },
    emptyState: "Platform health data unavailable",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=platform-health",
  },
  {
    id: "pulse-feed",
    name: "The Pulse",
    category: "operations",
    dataProvider: "pulse.recent",
    refreshPolicy: { mode: "polling", intervalSeconds: 15, sseEndpoint: "/pulse/stream" },
    permissions: [],
    layout: { defaultWidth: 2, defaultHeight: "tall", order: 1, collapsible: true, resizable: true, exportable: true },
    emptyState: "No heartbeats yet. Create memory, bills, or sync GitHub to emit pulses.",
    supportsMultipleInstances: true,
    deepLinkPath: "/dashboard/mission-control?widget=pulse-feed",
  },
  {
    id: "operational-timeline",
    name: "Operational Timeline",
    category: "operations",
    dataProvider: "operational-timeline",
    refreshPolicy: { mode: "polling", intervalSeconds: 30 },
    permissions: [],
    layout: { defaultWidth: 2, defaultHeight: "standard", order: 2, collapsible: true, resizable: true, exportable: true },
    emptyState: "No platform events recorded yet.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=operational-timeline",
  },
  {
    id: "integrations-health",
    name: "Integrations",
    category: "integration",
    dataProvider: "integration.health",
    refreshPolicy: { mode: "polling", intervalSeconds: 60 },
    permissions: [],
    actions: ["integration.retry-sync"],
    layout: { defaultWidth: 1, defaultHeight: "standard", order: 3, collapsible: true, resizable: true, exportable: true },
    emptyState: "No integrations connected.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=integrations-health",
  },
  {
    id: "recommendations",
    name: "Recommendations",
    category: "intelligence",
    dataProvider: "intelligence.recommendations",
    refreshPolicy: { mode: "polling", intervalSeconds: 60 },
    permissions: [],
    actions: ["recommendation.approve", "recommendation.reject"],
    layout: { defaultWidth: 1, defaultHeight: "standard", order: 4, collapsible: true, resizable: true, exportable: true },
    emptyState: "No open recommendations.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=recommendations",
  },
  {
    id: "upcoming-bills",
    name: "Upcoming Bills",
    category: "finance",
    dataProvider: "billing.upcoming",
    refreshPolicy: { mode: "polling", intervalSeconds: 300 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "compact", order: 5, collapsible: true, resizable: true, exportable: true },
    emptyState: "No bills tracked.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=upcoming-bills",
  },
  {
    id: "timeline-today",
    name: "Today's Timeline",
    category: "operations",
    dataProvider: "timeline.recent",
    refreshPolicy: { mode: "polling", intervalSeconds: 60 },
    permissions: [],
    actions: ["meeting.schedule", "task.create"],
    layout: { defaultWidth: 1, defaultHeight: "standard", order: 6, collapsible: true, resizable: true, exportable: true },
    emptyState: "No events scheduled today.",
    supportsMultipleInstances: true,
    deepLinkPath: "/dashboard/mission-control?widget=timeline-today",
  },
  {
    id: "graph-summary",
    name: "Knowledge Graph",
    category: "engineering",
    dataProvider: "graph.summary",
    refreshPolicy: { mode: "polling", intervalSeconds: 300 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "compact", order: 7, collapsible: true, resizable: true, exportable: true },
    emptyState: "Graph is empty. Events will populate nodes automatically.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=graph-summary",
  },
  {
    id: "readiness-matrix",
    name: "Company Readiness",
    category: "health",
    dataProvider: "readiness",
    refreshPolicy: { mode: "polling", intervalSeconds: 300 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "standard", order: 8, collapsible: true, resizable: true, exportable: true },
    emptyState: "Readiness data not yet computed.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=readiness-matrix",
  },
  {
    id: "founder-brief",
    name: "Founder Brief",
    category: "brief",
    dataProvider: "founder-brief",
    refreshPolicy: { mode: "manual", intervalSeconds: 86400 },
    permissions: [],
    layout: { defaultWidth: 2, defaultHeight: "standard", order: 9, collapsible: true, resizable: true, exportable: true },
    emptyState: "Brief will assemble on first load.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=founder-brief",
  },
  {
    id: "plugin-status",
    name: "Plugins",
    category: "integration",
    dataProvider: "plugin.health",
    refreshPolicy: { mode: "polling", intervalSeconds: 60 },
    permissions: [],
    actions: ["plugin.install"],
    layout: { defaultWidth: 1, defaultHeight: "compact", order: 10, collapsible: true, resizable: true, exportable: true },
    emptyState: "No plugins installed.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=plugin-status",
  },
  {
    id: "integration-cost",
    name: "Integration Costs",
    category: "finance",
    dataProvider: "integration.cost",
    refreshPolicy: { mode: "polling", intervalSeconds: 300 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "compact", order: 11, collapsible: true, resizable: true, exportable: true },
    emptyState: "No integration usage recorded.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=integration-cost",
  },
  {
    id: "reliability-dashboard",
    name: "Platform Reliability",
    category: "health",
    dataProvider: "operations.reliability",
    refreshPolicy: { mode: "polling", intervalSeconds: 60 },
    permissions: [],
    layout: { defaultWidth: 2, defaultHeight: "standard", order: 12, collapsible: true, resizable: true, exportable: true },
    emptyState: "Reliability profiles not yet computed.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=reliability-dashboard",
  },
  {
    id: "diagnostics-panel",
    name: "Diagnostics",
    category: "operations",
    dataProvider: "operations.diagnostics",
    refreshPolicy: { mode: "polling", intervalSeconds: 120 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "standard", order: 13, collapsible: true, resizable: true, exportable: true },
    emptyState: "No diagnostic findings.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=diagnostics-panel",
  },
  {
    id: "performance-metrics",
    name: "Performance Metrics",
    category: "operations",
    dataProvider: "operations.metrics",
    refreshPolicy: { mode: "polling", intervalSeconds: 60 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "compact", order: 14, collapsible: true, resizable: true, exportable: true },
    emptyState: "Metrics not yet collected.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=performance-metrics",
  },
  {
    id: "platform-cost",
    name: "Platform Cost",
    category: "finance",
    dataProvider: "operations.cost",
    refreshPolicy: { mode: "polling", intervalSeconds: 300 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "compact", order: 15, collapsible: true, resizable: true, exportable: true },
    emptyState: "Cost breakdown unavailable.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=platform-cost",
  },
  {
    id: "foundation-readiness",
    name: "Foundation Readiness",
    category: "health",
    dataProvider: "operations.readiness",
    refreshPolicy: { mode: "polling", intervalSeconds: 300 },
    permissions: [],
    layout: { defaultWidth: 2, defaultHeight: "standard", order: 16, collapsible: false, resizable: true, exportable: true },
    emptyState: "Generate Platform Readiness Report via POST /platform/operations/readiness/generate",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=foundation-readiness",
  },
  {
    id: "platform-evolution",
    name: "Platform Evolution",
    category: "engineering",
    dataProvider: "operations.evolution",
    refreshPolicy: { mode: "polling", intervalSeconds: 600 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "compact", order: 17, collapsible: true, resizable: true, exportable: true },
    emptyState: "Version information unavailable.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=platform-evolution",
  },
  {
    id: "security-health",
    name: "Security Health",
    category: "health",
    dataProvider: "operations.security",
    refreshPolicy: { mode: "polling", intervalSeconds: 120 },
    permissions: [],
    layout: { defaultWidth: 1, defaultHeight: "standard", order: 18, collapsible: true, resizable: true, exportable: true },
    emptyState: "Security assessment unavailable.",
    supportsMultipleInstances: false,
    deepLinkPath: "/dashboard/mission-control?widget=security-health",
  },
];

@Injectable()
export class WidgetCatalogService {
  list(): MissionControlWidgetDefinition[] {
    return DEFAULT_WIDGETS;
  }

  get(widgetId: string): MissionControlWidgetDefinition | undefined {
    return DEFAULT_WIDGETS.find((w) => w.id === widgetId);
  }

  defaultLayout(): WidgetInstanceConfig[] {
    return DEFAULT_WIDGETS.map((w, i) => ({
      instanceId: `${w.id}-default`,
      widgetId: w.id,
      visible: true,
      order: i,
      collapsed: false,
      pinned: w.id === "platform-health" || w.id === "pulse-feed",
      favorite: false,
      width: w.layout.defaultWidth,
      height: w.layout.defaultHeight,
    }));
  }
}
